//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 03:00:48 PM CET 
//


package it.kdm.docer.core.authentication;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.kdm.docer.core.authentication package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AuthenticationServiceExceptionAuthenticationServiceException_QNAME = new QName("http://authentication.core.docer.kdm.it", "AuthenticationServiceException");
    private final static QName _GetUserInfoToken_QNAME = new QName("http://authentication.core.docer.kdm.it", "token");
    private final static QName _LoginOnDemandServiceName_QNAME = new QName("http://authentication.core.docer.kdm.it", "serviceName");
    private final static QName _LoginOnDemandServiceUrl_QNAME = new QName("http://authentication.core.docer.kdm.it", "serviceUrl");
    private final static QName _LoginOnDemandResponseReturn_QNAME = new QName("http://authentication.core.docer.kdm.it", "return");
    private final static QName _LoginUsername_QNAME = new QName("http://authentication.core.docer.kdm.it", "username");
    private final static QName _LoginPassword_QNAME = new QName("http://authentication.core.docer.kdm.it", "password");
    private final static QName _LoginCodiceEnte_QNAME = new QName("http://authentication.core.docer.kdm.it", "codiceEnte");
    private final static QName _LoginApplication_QNAME = new QName("http://authentication.core.docer.kdm.it", "application");
    private final static QName _LoginSSOJwtToken_QNAME = new QName("http://authentication.core.docer.kdm.it", "jwtToken");
    private final static QName _ExceptionMessage_QNAME = new QName("http://authentication.core.docer.kdm.it", "Message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.kdm.docer.core.authentication
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthenticationServiceException }
     * 
     */
    public AuthenticationServiceException createAuthenticationServiceException() {
        return new AuthenticationServiceException();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link GetUserInfo }
     * 
     */
    public GetUserInfo createGetUserInfo() {
        return new GetUserInfo();
    }

    /**
     * Create an instance of {@link GetUserInfoResponse }
     * 
     */
    public GetUserInfoResponse createGetUserInfoResponse() {
        return new GetUserInfoResponse();
    }

    /**
     * Create an instance of {@link VerifyToken }
     * 
     */
    public VerifyToken createVerifyToken() {
        return new VerifyToken();
    }

    /**
     * Create an instance of {@link VerifyTokenResponse }
     * 
     */
    public VerifyTokenResponse createVerifyTokenResponse() {
        return new VerifyTokenResponse();
    }

    /**
     * Create an instance of {@link LoginOnDemand }
     * 
     */
    public LoginOnDemand createLoginOnDemand() {
        return new LoginOnDemand();
    }

    /**
     * Create an instance of {@link LoginOnDemandResponse }
     * 
     */
    public LoginOnDemandResponse createLoginOnDemandResponse() {
        return new LoginOnDemandResponse();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link Logout }
     * 
     */
    public Logout createLogout() {
        return new Logout();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link LoginSSO }
     * 
     */
    public LoginSSO createLoginSSO() {
        return new LoginSSO();
    }

    /**
     * Create an instance of {@link LoginSSOResponse }
     * 
     */
    public LoginSSOResponse createLoginSSOResponse() {
        return new LoginSSOResponse();
    }

    /**
     * Create an instance of {@link GetRealUser }
     * 
     */
    public GetRealUser createGetRealUser() {
        return new GetRealUser();
    }

    /**
     * Create an instance of {@link GetRealUserResponse }
     * 
     */
    public GetRealUserResponse createGetRealUserResponse() {
        return new GetRealUserResponse();
    }

    /**
     * Create an instance of {@link GetEnteDescription }
     * 
     */
    public GetEnteDescription createGetEnteDescription() {
        return new GetEnteDescription();
    }

    /**
     * Create an instance of {@link GetEnteDescriptionResponse }
     * 
     */
    public GetEnteDescriptionResponse createGetEnteDescriptionResponse() {
        return new GetEnteDescriptionResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "AuthenticationServiceException", scope = AuthenticationServiceException.class)
    public JAXBElement<Exception> createAuthenticationServiceExceptionAuthenticationServiceException(Exception value) {
        return new JAXBElement<Exception>(_AuthenticationServiceExceptionAuthenticationServiceException_QNAME, Exception.class, AuthenticationServiceException.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "token", scope = GetUserInfo.class)
    public JAXBElement<String> createGetUserInfoToken(String value) {
        return new JAXBElement<String>(_GetUserInfoToken_QNAME, String.class, GetUserInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "token", scope = VerifyToken.class)
    public JAXBElement<String> createVerifyTokenToken(String value) {
        return new JAXBElement<String>(_GetUserInfoToken_QNAME, String.class, VerifyToken.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "token", scope = LoginOnDemand.class)
    public JAXBElement<String> createLoginOnDemandToken(String value) {
        return new JAXBElement<String>(_GetUserInfoToken_QNAME, String.class, LoginOnDemand.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "serviceName", scope = LoginOnDemand.class)
    public JAXBElement<String> createLoginOnDemandServiceName(String value) {
        return new JAXBElement<String>(_LoginOnDemandServiceName_QNAME, String.class, LoginOnDemand.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "serviceUrl", scope = LoginOnDemand.class)
    public JAXBElement<String> createLoginOnDemandServiceUrl(String value) {
        return new JAXBElement<String>(_LoginOnDemandServiceUrl_QNAME, String.class, LoginOnDemand.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "return", scope = LoginOnDemandResponse.class)
    public JAXBElement<String> createLoginOnDemandResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, LoginOnDemandResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "username", scope = Login.class)
    public JAXBElement<String> createLoginUsername(String value) {
        return new JAXBElement<String>(_LoginUsername_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "password", scope = Login.class)
    public JAXBElement<String> createLoginPassword(String value) {
        return new JAXBElement<String>(_LoginPassword_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "codiceEnte", scope = Login.class)
    public JAXBElement<String> createLoginCodiceEnte(String value) {
        return new JAXBElement<String>(_LoginCodiceEnte_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "application", scope = Login.class)
    public JAXBElement<String> createLoginApplication(String value) {
        return new JAXBElement<String>(_LoginApplication_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "return", scope = LoginResponse.class)
    public JAXBElement<String> createLoginResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, LoginResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "token", scope = Logout.class)
    public JAXBElement<String> createLogoutToken(String value) {
        return new JAXBElement<String>(_GetUserInfoToken_QNAME, String.class, Logout.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "jwtToken", scope = LoginSSO.class)
    public JAXBElement<String> createLoginSSOJwtToken(String value) {
        return new JAXBElement<String>(_LoginSSOJwtToken_QNAME, String.class, LoginSSO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "codiceEnte", scope = LoginSSO.class)
    public JAXBElement<String> createLoginSSOCodiceEnte(String value) {
        return new JAXBElement<String>(_LoginCodiceEnte_QNAME, String.class, LoginSSO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "application", scope = LoginSSO.class)
    public JAXBElement<String> createLoginSSOApplication(String value) {
        return new JAXBElement<String>(_LoginApplication_QNAME, String.class, LoginSSO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "return", scope = LoginSSOResponse.class)
    public JAXBElement<String> createLoginSSOResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, LoginSSOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "jwtToken", scope = GetRealUser.class)
    public JAXBElement<String> createGetRealUserJwtToken(String value) {
        return new JAXBElement<String>(_LoginSSOJwtToken_QNAME, String.class, GetRealUser.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "return", scope = GetRealUserResponse.class)
    public JAXBElement<String> createGetRealUserResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, GetRealUserResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "token", scope = GetEnteDescription.class)
    public JAXBElement<String> createGetEnteDescriptionToken(String value) {
        return new JAXBElement<String>(_GetUserInfoToken_QNAME, String.class, GetEnteDescription.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "return", scope = GetEnteDescriptionResponse.class)
    public JAXBElement<String> createGetEnteDescriptionResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, GetEnteDescriptionResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://authentication.core.docer.kdm.it", name = "Message", scope = Exception.class)
    public JAXBElement<String> createExceptionMessage(String value) {
        return new JAXBElement<String>(_ExceptionMessage_QNAME, String.class, Exception.class, value);
    }

}
