//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:28:12 PM CET 
//


package it.kdm.docer.protocollazione;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import it.kdm.docer.protocollazione.xsd.ProtocollazioneException;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.kdm.docer.protocollazione package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WSProtocollazioneExceptionWSProtocollazioneException_QNAME = new QName("http://protocollazione.docer.kdm.it", "WSProtocollazioneException");
    private final static QName _LoginOnDemandUserId_QNAME = new QName("http://protocollazione.docer.kdm.it", "userId");
    private final static QName _LoginOnDemandPassword_QNAME = new QName("http://protocollazione.docer.kdm.it", "password");
    private final static QName _LoginOnDemandCodiceEnte_QNAME = new QName("http://protocollazione.docer.kdm.it", "codiceEnte");
    private final static QName _LoginOnDemandCodiceAoo_QNAME = new QName("http://protocollazione.docer.kdm.it", "codiceAoo");
    private final static QName _LoginOnDemandDocTicket_QNAME = new QName("http://protocollazione.docer.kdm.it", "docTicket");
    private final static QName _LoginOnDemandResponseReturn_QNAME = new QName("http://protocollazione.docer.kdm.it", "return");
    private final static QName _WSProtocollazioneProtocollazioneExceptionProtocollazioneException_QNAME = new QName("http://protocollazione.docer.kdm.it", "ProtocollazioneException");
    private final static QName _LogoutToken_QNAME = new QName("http://protocollazione.docer.kdm.it", "token");
    private final static QName _ProtocollaByIdDatiProtocollo_QNAME = new QName("http://protocollazione.docer.kdm.it", "datiProtocollo");
    private final static QName _LoginSSOSaml_QNAME = new QName("http://protocollazione.docer.kdm.it", "saml");
    private final static QName _WriteConfigXmlConfig_QNAME = new QName("http://protocollazione.docer.kdm.it", "xmlConfig");
    private final static QName _ExceptionMessage_QNAME = new QName("http://protocollazione.docer.kdm.it", "Message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.kdm.docer.protocollazione
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSProtocollazioneException }
     * 
     */
    public WSProtocollazioneException createWSProtocollazioneException() {
        return new WSProtocollazioneException();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link LoginOnDemand }
     * 
     */
    public LoginOnDemand createLoginOnDemand() {
        return new LoginOnDemand();
    }

    /**
     * Create an instance of {@link LoginOnDemandResponse }
     * 
     */
    public LoginOnDemandResponse createLoginOnDemandResponse() {
        return new LoginOnDemandResponse();
    }

    /**
     * Create an instance of {@link WSProtocollazioneProtocollazioneException }
     * 
     */
    public WSProtocollazioneProtocollazioneException createWSProtocollazioneProtocollazioneException() {
        return new WSProtocollazioneProtocollazioneException();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link Logout }
     * 
     */
    public Logout createLogout() {
        return new Logout();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link ProtocollaById }
     * 
     */
    public ProtocollaById createProtocollaById() {
        return new ProtocollaById();
    }

    /**
     * Create an instance of {@link ProtocollaByIdResponse }
     * 
     */
    public ProtocollaByIdResponse createProtocollaByIdResponse() {
        return new ProtocollaByIdResponse();
    }

    /**
     * Create an instance of {@link LoginSSO }
     * 
     */
    public LoginSSO createLoginSSO() {
        return new LoginSSO();
    }

    /**
     * Create an instance of {@link LoginSSOResponse }
     * 
     */
    public LoginSSOResponse createLoginSSOResponse() {
        return new LoginSSOResponse();
    }

    /**
     * Create an instance of {@link ReadConfig }
     * 
     */
    public ReadConfig createReadConfig() {
        return new ReadConfig();
    }

    /**
     * Create an instance of {@link ReadConfigResponse }
     * 
     */
    public ReadConfigResponse createReadConfigResponse() {
        return new ReadConfigResponse();
    }

    /**
     * Create an instance of {@link WriteConfig }
     * 
     */
    public WriteConfig createWriteConfig() {
        return new WriteConfig();
    }

    /**
     * Create an instance of {@link WriteConfigResponse }
     * 
     */
    public WriteConfigResponse createWriteConfigResponse() {
        return new WriteConfigResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "WSProtocollazioneException", scope = WSProtocollazioneException.class)
    public JAXBElement<Exception> createWSProtocollazioneExceptionWSProtocollazioneException(Exception value) {
        return new JAXBElement<Exception>(_WSProtocollazioneExceptionWSProtocollazioneException_QNAME, Exception.class, WSProtocollazioneException.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "userId", scope = LoginOnDemand.class)
    public JAXBElement<String> createLoginOnDemandUserId(String value) {
        return new JAXBElement<String>(_LoginOnDemandUserId_QNAME, String.class, LoginOnDemand.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "password", scope = LoginOnDemand.class)
    public JAXBElement<String> createLoginOnDemandPassword(String value) {
        return new JAXBElement<String>(_LoginOnDemandPassword_QNAME, String.class, LoginOnDemand.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "codiceEnte", scope = LoginOnDemand.class)
    public JAXBElement<String> createLoginOnDemandCodiceEnte(String value) {
        return new JAXBElement<String>(_LoginOnDemandCodiceEnte_QNAME, String.class, LoginOnDemand.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "codiceAoo", scope = LoginOnDemand.class)
    public JAXBElement<String> createLoginOnDemandCodiceAoo(String value) {
        return new JAXBElement<String>(_LoginOnDemandCodiceAoo_QNAME, String.class, LoginOnDemand.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "docTicket", scope = LoginOnDemand.class)
    public JAXBElement<String> createLoginOnDemandDocTicket(String value) {
        return new JAXBElement<String>(_LoginOnDemandDocTicket_QNAME, String.class, LoginOnDemand.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "return", scope = LoginOnDemandResponse.class)
    public JAXBElement<String> createLoginOnDemandResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, LoginOnDemandResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtocollazioneException }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ProtocollazioneException }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "ProtocollazioneException", scope = WSProtocollazioneProtocollazioneException.class)
    public JAXBElement<ProtocollazioneException> createWSProtocollazioneProtocollazioneExceptionProtocollazioneException(ProtocollazioneException value) {
        return new JAXBElement<ProtocollazioneException>(_WSProtocollazioneProtocollazioneExceptionProtocollazioneException_QNAME, ProtocollazioneException.class, WSProtocollazioneProtocollazioneException.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "userId", scope = Login.class)
    public JAXBElement<String> createLoginUserId(String value) {
        return new JAXBElement<String>(_LoginOnDemandUserId_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "password", scope = Login.class)
    public JAXBElement<String> createLoginPassword(String value) {
        return new JAXBElement<String>(_LoginOnDemandPassword_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "codiceEnte", scope = Login.class)
    public JAXBElement<String> createLoginCodiceEnte(String value) {
        return new JAXBElement<String>(_LoginOnDemandCodiceEnte_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "return", scope = LoginResponse.class)
    public JAXBElement<String> createLoginResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, LoginResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "token", scope = Logout.class)
    public JAXBElement<String> createLogoutToken(String value) {
        return new JAXBElement<String>(_LogoutToken_QNAME, String.class, Logout.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "token", scope = ProtocollaById.class)
    public JAXBElement<String> createProtocollaByIdToken(String value) {
        return new JAXBElement<String>(_LogoutToken_QNAME, String.class, ProtocollaById.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "datiProtocollo", scope = ProtocollaById.class)
    public JAXBElement<String> createProtocollaByIdDatiProtocollo(String value) {
        return new JAXBElement<String>(_ProtocollaByIdDatiProtocollo_QNAME, String.class, ProtocollaById.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "return", scope = ProtocollaByIdResponse.class)
    public JAXBElement<String> createProtocollaByIdResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, ProtocollaByIdResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "saml", scope = LoginSSO.class)
    public JAXBElement<String> createLoginSSOSaml(String value) {
        return new JAXBElement<String>(_LoginSSOSaml_QNAME, String.class, LoginSSO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "codiceEnte", scope = LoginSSO.class)
    public JAXBElement<String> createLoginSSOCodiceEnte(String value) {
        return new JAXBElement<String>(_LoginOnDemandCodiceEnte_QNAME, String.class, LoginSSO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "return", scope = LoginSSOResponse.class)
    public JAXBElement<String> createLoginSSOResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, LoginSSOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "token", scope = ReadConfig.class)
    public JAXBElement<String> createReadConfigToken(String value) {
        return new JAXBElement<String>(_LogoutToken_QNAME, String.class, ReadConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "return", scope = ReadConfigResponse.class)
    public JAXBElement<String> createReadConfigResponseReturn(String value) {
        return new JAXBElement<String>(_LoginOnDemandResponseReturn_QNAME, String.class, ReadConfigResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "token", scope = WriteConfig.class)
    public JAXBElement<String> createWriteConfigToken(String value) {
        return new JAXBElement<String>(_LogoutToken_QNAME, String.class, WriteConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "xmlConfig", scope = WriteConfig.class)
    public JAXBElement<String> createWriteConfigXmlConfig(String value) {
        return new JAXBElement<String>(_WriteConfigXmlConfig_QNAME, String.class, WriteConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://protocollazione.docer.kdm.it", name = "Message", scope = Exception.class)
    public JAXBElement<String> createExceptionMessage(String value) {
        return new JAXBElement<String>(_ExceptionMessage_QNAME, String.class, Exception.class, value);
    }

}
