//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:27:24 PM CET 
//


package it.kdm.docer.registrazione;

import it.kdm.docer.registrazione.xsd.RegistrazioneException;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.kdm.docer.registrazione package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WSRegistrazioneRegistrazioneExceptionRegistrazioneException_QNAME = new QName("http://registrazione.docer.kdm.it", "RegistrazioneException");
    private final static QName _LoginUserId_QNAME = new QName("http://registrazione.docer.kdm.it", "userId");
    private final static QName _LoginPassword_QNAME = new QName("http://registrazione.docer.kdm.it", "password");
    private final static QName _LoginCodiceEnte_QNAME = new QName("http://registrazione.docer.kdm.it", "codiceEnte");
    private final static QName _LoginResponseReturn_QNAME = new QName("http://registrazione.docer.kdm.it", "return");
    private final static QName _LogoutToken_QNAME = new QName("http://registrazione.docer.kdm.it", "token");
    private final static QName _RegistraByIdRegistroId_QNAME = new QName("http://registrazione.docer.kdm.it", "registroId");
    private final static QName _RegistraByIdDatiRegistrazione_QNAME = new QName("http://registrazione.docer.kdm.it", "datiRegistrazione");
    private final static QName _GetRegistriCodEnte_QNAME = new QName("http://registrazione.docer.kdm.it", "cod_ente");
    private final static QName _GetRegistriCodAoo_QNAME = new QName("http://registrazione.docer.kdm.it", "cod_aoo");
    private final static QName _LoginSSOSaml_QNAME = new QName("http://registrazione.docer.kdm.it", "saml");
    private final static QName _WriteConfigXmlConfig_QNAME = new QName("http://registrazione.docer.kdm.it", "xmlConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.kdm.docer.registrazione
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSRegistrazioneRegistrazioneException }
     * 
     */
    public WSRegistrazioneRegistrazioneException createWSRegistrazioneRegistrazioneException() {
        return new WSRegistrazioneRegistrazioneException();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link Logout }
     * 
     */
    public Logout createLogout() {
        return new Logout();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link RegistraById }
     * 
     */
    public RegistraById createRegistraById() {
        return new RegistraById();
    }

    /**
     * Create an instance of {@link RegistraByIdResponse }
     * 
     */
    public RegistraByIdResponse createRegistraByIdResponse() {
        return new RegistraByIdResponse();
    }

    /**
     * Create an instance of {@link GetRegistri }
     * 
     */
    public GetRegistri createGetRegistri() {
        return new GetRegistri();
    }

    /**
     * Create an instance of {@link GetRegistriResponse }
     * 
     */
    public GetRegistriResponse createGetRegistriResponse() {
        return new GetRegistriResponse();
    }

    /**
     * Create an instance of {@link LoginSSO }
     * 
     */
    public LoginSSO createLoginSSO() {
        return new LoginSSO();
    }

    /**
     * Create an instance of {@link LoginSSOResponse }
     * 
     */
    public LoginSSOResponse createLoginSSOResponse() {
        return new LoginSSOResponse();
    }

    /**
     * Create an instance of {@link ReadConfig }
     * 
     */
    public ReadConfig createReadConfig() {
        return new ReadConfig();
    }

    /**
     * Create an instance of {@link ReadConfigResponse }
     * 
     */
    public ReadConfigResponse createReadConfigResponse() {
        return new ReadConfigResponse();
    }

    /**
     * Create an instance of {@link WriteConfig }
     * 
     */
    public WriteConfig createWriteConfig() {
        return new WriteConfig();
    }

    /**
     * Create an instance of {@link WriteConfigResponse }
     * 
     */
    public WriteConfigResponse createWriteConfigResponse() {
        return new WriteConfigResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistrazioneException }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegistrazioneException }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "RegistrazioneException", scope = WSRegistrazioneRegistrazioneException.class)
    public JAXBElement<RegistrazioneException> createWSRegistrazioneRegistrazioneExceptionRegistrazioneException(RegistrazioneException value) {
        return new JAXBElement<RegistrazioneException>(_WSRegistrazioneRegistrazioneExceptionRegistrazioneException_QNAME, RegistrazioneException.class, WSRegistrazioneRegistrazioneException.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "userId", scope = Login.class)
    public JAXBElement<String> createLoginUserId(String value) {
        return new JAXBElement<String>(_LoginUserId_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "password", scope = Login.class)
    public JAXBElement<String> createLoginPassword(String value) {
        return new JAXBElement<String>(_LoginPassword_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "codiceEnte", scope = Login.class)
    public JAXBElement<String> createLoginCodiceEnte(String value) {
        return new JAXBElement<String>(_LoginCodiceEnte_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "return", scope = LoginResponse.class)
    public JAXBElement<String> createLoginResponseReturn(String value) {
        return new JAXBElement<String>(_LoginResponseReturn_QNAME, String.class, LoginResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "token", scope = Logout.class)
    public JAXBElement<String> createLogoutToken(String value) {
        return new JAXBElement<String>(_LogoutToken_QNAME, String.class, Logout.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "token", scope = RegistraById.class)
    public JAXBElement<String> createRegistraByIdToken(String value) {
        return new JAXBElement<String>(_LogoutToken_QNAME, String.class, RegistraById.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "registroId", scope = RegistraById.class)
    public JAXBElement<String> createRegistraByIdRegistroId(String value) {
        return new JAXBElement<String>(_RegistraByIdRegistroId_QNAME, String.class, RegistraById.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "datiRegistrazione", scope = RegistraById.class)
    public JAXBElement<String> createRegistraByIdDatiRegistrazione(String value) {
        return new JAXBElement<String>(_RegistraByIdDatiRegistrazione_QNAME, String.class, RegistraById.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "return", scope = RegistraByIdResponse.class)
    public JAXBElement<String> createRegistraByIdResponseReturn(String value) {
        return new JAXBElement<String>(_LoginResponseReturn_QNAME, String.class, RegistraByIdResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "token", scope = GetRegistri.class)
    public JAXBElement<String> createGetRegistriToken(String value) {
        return new JAXBElement<String>(_LogoutToken_QNAME, String.class, GetRegistri.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "cod_ente", scope = GetRegistri.class)
    public JAXBElement<String> createGetRegistriCodEnte(String value) {
        return new JAXBElement<String>(_GetRegistriCodEnte_QNAME, String.class, GetRegistri.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "cod_aoo", scope = GetRegistri.class)
    public JAXBElement<String> createGetRegistriCodAoo(String value) {
        return new JAXBElement<String>(_GetRegistriCodAoo_QNAME, String.class, GetRegistri.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "saml", scope = LoginSSO.class)
    public JAXBElement<String> createLoginSSOSaml(String value) {
        return new JAXBElement<String>(_LoginSSOSaml_QNAME, String.class, LoginSSO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "codiceEnte", scope = LoginSSO.class)
    public JAXBElement<String> createLoginSSOCodiceEnte(String value) {
        return new JAXBElement<String>(_LoginCodiceEnte_QNAME, String.class, LoginSSO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "return", scope = LoginSSOResponse.class)
    public JAXBElement<String> createLoginSSOResponseReturn(String value) {
        return new JAXBElement<String>(_LoginResponseReturn_QNAME, String.class, LoginSSOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "token", scope = ReadConfig.class)
    public JAXBElement<String> createReadConfigToken(String value) {
        return new JAXBElement<String>(_LogoutToken_QNAME, String.class, ReadConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "return", scope = ReadConfigResponse.class)
    public JAXBElement<String> createReadConfigResponseReturn(String value) {
        return new JAXBElement<String>(_LoginResponseReturn_QNAME, String.class, ReadConfigResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "token", scope = WriteConfig.class)
    public JAXBElement<String> createWriteConfigToken(String value) {
        return new JAXBElement<String>(_LogoutToken_QNAME, String.class, WriteConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://registrazione.docer.kdm.it", name = "xmlConfig", scope = WriteConfig.class)
    public JAXBElement<String> createWriteConfigXmlConfig(String value) {
        return new JAXBElement<String>(_WriteConfigXmlConfig_QNAME, String.class, WriteConfig.class, value);
    }

}
