//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:27:24 PM CET 
//


package it.kdm.docer.registrazione;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import it.kdm.docer.registrazione.xsd.RegistrazioneException;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RegistrazioneException" type="{http://registrazione.docer.kdm.it/xsd}RegistrazioneException" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "registrazioneException"
})
@XmlRootElement(name = "WSRegistrazioneRegistrazioneException")
public class WSRegistrazioneRegistrazioneException {

    @XmlElementRef(name = "RegistrazioneException", namespace = "http://registrazione.docer.kdm.it", type = JAXBElement.class, required = false)
    protected JAXBElement<RegistrazioneException> registrazioneException;

    /**
     * Gets the value of the registrazioneException property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RegistrazioneException }{@code >}
     *     
     */
    public JAXBElement<RegistrazioneException> getRegistrazioneException() {
        return registrazioneException;
    }

    /**
     * Sets the value of the registrazioneException property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RegistrazioneException }{@code >}
     *     
     */
    public void setRegistrazioneException(JAXBElement<RegistrazioneException> value) {
        this.registrazioneException = value;
    }

}
