//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 03:00:48 PM CET 
//


package org.apache.commons.collections.keyvalue.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.commons.collections.keyvalue.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AbstractKeyValueKey_QNAME = new QName("http://keyvalue.collections.commons.apache.org/xsd", "key");
    private final static QName _AbstractKeyValueValue_QNAME = new QName("http://keyvalue.collections.commons.apache.org/xsd", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.commons.collections.keyvalue.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AbstractKeyValue }
     * 
     */
    public AbstractKeyValue createAbstractKeyValue() {
        return new AbstractKeyValue();
    }

    /**
     * Create an instance of {@link DefaultKeyValue }
     * 
     */
    public DefaultKeyValue createDefaultKeyValue() {
        return new DefaultKeyValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://keyvalue.collections.commons.apache.org/xsd", name = "key", scope = AbstractKeyValue.class)
    public JAXBElement<Object> createAbstractKeyValueKey(Object value) {
        return new JAXBElement<Object>(_AbstractKeyValueKey_QNAME, Object.class, AbstractKeyValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://keyvalue.collections.commons.apache.org/xsd", name = "value", scope = AbstractKeyValue.class)
    public JAXBElement<Object> createAbstractKeyValueValue(Object value) {
        return new JAXBElement<Object>(_AbstractKeyValueValue_QNAME, Object.class, AbstractKeyValue.class, value);
    }

}
