//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.16 at 12:50:56 AM CET 
//


package it.kdm.docer.sdk.exceptions.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.kdm.docer.sdk.exceptions.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocerExceptionErrDescription_QNAME = new QName("http://exceptions.sdk.docer.kdm.it/xsd", "errDescription");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.kdm.docer.sdk.exceptions.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocerException }
     * 
     */
    public DocerException createDocerException() {
        return new DocerException();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://exceptions.sdk.docer.kdm.it/xsd", name = "errDescription", scope = DocerException.class)
    public JAXBElement<String> createDocerExceptionErrDescription(String value) {
        return new JAXBElement<String>(_DocerExceptionErrDescription_QNAME, String.class, DocerException.class, value);
    }

}
