//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.16 at 12:50:56 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://exceptions.sdk.docer.kdm.it/xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.kdm.docer.sdk.exceptions.xsd;
