//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.16 at 12:50:56 AM CET 
//


package it.kdm.docer.webservices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import it.kdm.docer.sdk.exceptions.xsd.DocerException;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocerException" type="{http://exceptions.sdk.docer.kdm.it/xsd}DocerException" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "docerException"
})
@XmlRootElement(name = "DocerServicesDocerException")
public class DocerServicesDocerException {

    @XmlElementRef(name = "DocerException", namespace = "http://webservices.docer.kdm.it", type = JAXBElement.class, required = false)
    protected JAXBElement<DocerException> docerException;

    /**
     * Gets the value of the docerException property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DocerException }{@code >}
     *     
     */
    public JAXBElement<DocerException> getDocerException() {
        return docerException;
    }

    /**
     * Sets the value of the docerException property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DocerException }{@code >}
     *     
     */
    public void setDocerException(JAXBElement<DocerException> value) {
        this.docerException = value;
    }

}
