
package it.filippetti.ks.api.payment.pmpay.authpa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthPASoap", targetNamespace = "http://pmPay.it/ws/authPA/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthPASoap {


    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTicket", action = "http://pmPay.it/ws/authPA/GetTicket")
    @WebResult(name = "GetTicketResult", targetNamespace = "http://pmPay.it/ws/authPA/")
    @RequestWrapper(localName = "GetTicket", targetNamespace = "http://pmPay.it/ws/authPA/", className = "it.pmpay.ws.authpa.GetTicket")
    @ResponseWrapper(localName = "GetTicketResponse", targetNamespace = "http://pmPay.it/ws/authPA/", className = "it.pmpay.ws.authpa.GetTicketResponse")
    public String getTicket(
        @WebParam(name = "content", targetNamespace = "http://pmPay.it/ws/authPA/")
        String content);

    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetIUV", action = "http://pmPay.it/ws/authPA/GetIUV")
    @WebResult(name = "GetIUVResult", targetNamespace = "http://pmPay.it/ws/authPA/")
    @RequestWrapper(localName = "GetIUV", targetNamespace = "http://pmPay.it/ws/authPA/", className = "it.pmpay.ws.authpa.GetIUV")
    @ResponseWrapper(localName = "GetIUVResponse", targetNamespace = "http://pmPay.it/ws/authPA/", className = "it.pmpay.ws.authpa.GetIUVResponse")
    public String getIUV(
        @WebParam(name = "content", targetNamespace = "http://pmPay.it/ws/authPA/")
        String content);

}
