package it.filippetti.ks.api.payment.bnl.pay;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "PaymentInitGateway", targetNamespace = "http://services.api.web.cg.igfs.apps.netsw.it/", wsdlLocation = "file:/home/roberta/Scaricati/PaymentInitGatewayPort.wsdl")
public class PaymentInitGateway_Service
    extends Service
{

    private final static URL PAYMENTINITGATEWAY_WSDL_LOCATION;
    private final static WebServiceException PAYMENTINITGATEWAY_EXCEPTION;
    private final static QName PAYMENTINITGATEWAY_QNAME = new QName("http://services.api.web.cg.igfs.apps.netsw.it/", "PaymentInitGateway");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/roberta/Scaricati/PaymentInitGatewayPort.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTINITGATEWAY_WSDL_LOCATION = url;
        PAYMENTINITGATEWAY_EXCEPTION = e;
    }

    public PaymentInitGateway_Service() {
        super(__getWsdlLocation(), PAYMENTINITGATEWAY_QNAME);
    }

    public PaymentInitGateway_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTINITGATEWAY_QNAME, features);
    }

    public PaymentInitGateway_Service(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTINITGATEWAY_QNAME);
    }

    public PaymentInitGateway_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTINITGATEWAY_QNAME, features);
    }

    public PaymentInitGateway_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentInitGateway_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PaymentInitGateway
     */
    @WebEndpoint(name = "PaymentInitGatewayPort")
    public PaymentInitGateway getPaymentInitGatewayPort() {
        return super.getPort(new QName("http://services.api.web.cg.igfs.apps.netsw.it/", "PaymentInitGatewayPort"), PaymentInitGateway.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentInitGateway
     */
    @WebEndpoint(name = "PaymentInitGatewayPort")
    public PaymentInitGateway getPaymentInitGatewayPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.api.web.cg.igfs.apps.netsw.it/", "PaymentInitGatewayPort"), PaymentInitGateway.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTINITGATEWAY_EXCEPTION!= null) {
            throw PAYMENTINITGATEWAY_EXCEPTION;
        }
        return PAYMENTINITGATEWAY_WSDL_LOCATION;
    }

}
