package it.filippetti.ks.api.payment.bnl.pay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentInitGateway", targetNamespace = "http://services.api.web.cg.igfs.apps.netsw.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentInitGateway {


    /**
     * 
     * @param parameters
     * @return
     *     returns it.pianetacloud.idea.web.bnl.pay.InitResponse
     */
    @WebMethod
    @WebResult(name = "InitResponse", targetNamespace = "http://services.api.web.cg.igfs.apps.netsw.it/", partName = "parameters")
    public InitResponse init(
        @WebParam(name = "Init", targetNamespace = "http://services.api.web.cg.igfs.apps.netsw.it/", partName = "parameters")
        Init parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns it.pianetacloud.idea.web.bnl.pay.VerifyResponse
     */
    @WebMethod
    @WebResult(name = "VerifyResponse", targetNamespace = "http://services.api.web.cg.igfs.apps.netsw.it/", partName = "parameters")
    public VerifyResponse verify(
        @WebParam(name = "Verify", targetNamespace = "http://services.api.web.cg.igfs.apps.netsw.it/", partName = "parameters")
        Verify parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns it.pianetacloud.idea.web.bnl.pay.SelectorResponse
     */
    @WebMethod
    @WebResult(name = "SelectorResponse", targetNamespace = "http://services.api.web.cg.igfs.apps.netsw.it/", partName = "parameters")
    public SelectorResponse selector(
        @WebParam(name = "Selector", targetNamespace = "http://services.api.web.cg.igfs.apps.netsw.it/", partName = "parameters")
        Selector parameters);

}
