//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 06:06:43 PM CEST 
//


package it.filippetti.ks.api.payment.pmpay.authpa.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for headerRichiestaIUV complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="headerRichiestaIUV">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID_CLIENT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TOKEN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DATA_RICHIESTA" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ID_RICHIESTA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODICE_AZIENDA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "headerRichiestaIUV", propOrder = {
    "idclient",
    "token",
    "datarichiesta",
    "idrichiesta",
    "codiceazienda"
})
public class HeaderRichiestaIUV {

    @XmlElement(name = "ID_CLIENT", required = true)
    protected String idclient;
    @XmlElement(name = "TOKEN", required = true)
    protected String token;
    @XmlElement(name = "DATA_RICHIESTA", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datarichiesta;
    @XmlElement(name = "ID_RICHIESTA", required = true)
    protected String idrichiesta;
    @XmlElement(name = "CODICE_AZIENDA", required = true)
    protected String codiceazienda;

    /**
     * Gets the value of the idclient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDCLIENT() {
        return idclient;
    }

    /**
     * Sets the value of the idclient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDCLIENT(String value) {
        this.idclient = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOKEN() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOKEN(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the datarichiesta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATARICHIESTA() {
        return datarichiesta;
    }

    /**
     * Sets the value of the datarichiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATARICHIESTA(XMLGregorianCalendar value) {
        this.datarichiesta = value;
    }

    /**
     * Gets the value of the idrichiesta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDRICHIESTA() {
        return idrichiesta;
    }

    /**
     * Sets the value of the idrichiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDRICHIESTA(String value) {
        this.idrichiesta = value;
    }

    /**
     * Gets the value of the codiceazienda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODICEAZIENDA() {
        return codiceazienda;
    }

    /**
     * Sets the value of the codiceazienda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODICEAZIENDA(String value) {
        this.codiceazienda = value;
    }

}
