//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 06:06:43 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:authPA", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.filippetti.ks.api.payment.pmpay.authpa.jaxb;
