//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 06:06:43 PM CEST 
//


package it.filippetti.ks.api.payment.pmpay.authpa.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RICHIEDI_IUV_RESPONSE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RICHIEDI_IUV_RESPONSE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DATA_RICHIESTA" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ID_RICHIESTA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODICE_AZIENDA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IUV" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CODICE_ERRORE" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="DESCRIZIONE_ERRORE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RICHIEDI_IUV_RESPONSE", propOrder = {
    "datarichiesta",
    "idrichiesta",
    "codiceazienda",
    "iuv",
    "codiceerrore",
    "descrizioneerrore"
})
public class RICHIEDIIUVRESPONSE {

    @XmlElement(name = "DATA_RICHIESTA", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datarichiesta;
    @XmlElement(name = "ID_RICHIESTA", required = true)
    protected String idrichiesta;
    @XmlElement(name = "CODICE_AZIENDA", required = true)
    protected String codiceazienda;
    @XmlElement(name = "IUV", required = true)
    protected String iuv;
    @XmlElement(name = "CODICE_ERRORE")
    protected BigInteger codiceerrore;
    @XmlElement(name = "DESCRIZIONE_ERRORE")
    protected String descrizioneerrore;

    /**
     * Gets the value of the datarichiesta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATARICHIESTA() {
        return datarichiesta;
    }

    /**
     * Sets the value of the datarichiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATARICHIESTA(XMLGregorianCalendar value) {
        this.datarichiesta = value;
    }

    /**
     * Gets the value of the idrichiesta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDRICHIESTA() {
        return idrichiesta;
    }

    /**
     * Sets the value of the idrichiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDRICHIESTA(String value) {
        this.idrichiesta = value;
    }

    /**
     * Gets the value of the codiceazienda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODICEAZIENDA() {
        return codiceazienda;
    }

    /**
     * Sets the value of the codiceazienda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODICEAZIENDA(String value) {
        this.codiceazienda = value;
    }

    /**
     * Gets the value of the iuv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIUV() {
        return iuv;
    }

    /**
     * Sets the value of the iuv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIUV(String value) {
        this.iuv = value;
    }

    /**
     * Gets the value of the codiceerrore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCODICEERRORE() {
        return codiceerrore;
    }

    /**
     * Sets the value of the codiceerrore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCODICEERRORE(BigInteger value) {
        this.codiceerrore = value;
    }

    /**
     * Gets the value of the descrizioneerrore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIZIONEERRORE() {
        return descrizioneerrore;
    }

    /**
     * Sets the value of the descrizioneerrore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIZIONEERRORE(String value) {
        this.descrizioneerrore = value;
    }

}
