//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 06:06:43 PM CEST 
//


package it.filippetti.ks.api.payment.pmpay.authpa.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for richiestaIUV complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="richiestaIUV">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RIF_INTERNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TIPO_REFERENCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RIF_ALFANUMERICO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RIF_CONTABILE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RIF_COD_UTENTE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STANDARD_ISO" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "richiestaIUV", propOrder = {
    "rifinterno",
    "tiporeference",
    "rifalfanumerico",
    "rifcontabile",
    "rifcodutente",
    "standardiso"
})
public class RichiestaIUV {

    @XmlElement(name = "RIF_INTERNO")
    protected String rifinterno;
    @XmlElement(name = "TIPO_REFERENCE", required = true)
    protected String tiporeference;
    @XmlElement(name = "RIF_ALFANUMERICO")
    protected String rifalfanumerico;
    @XmlElement(name = "RIF_CONTABILE")
    protected String rifcontabile;
    @XmlElement(name = "RIF_COD_UTENTE")
    protected String rifcodutente;
    @XmlElement(name = "STANDARD_ISO")
    protected Boolean standardiso;

    /**
     * Gets the value of the rifinterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRIFINTERNO() {
        return rifinterno;
    }

    /**
     * Sets the value of the rifinterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRIFINTERNO(String value) {
        this.rifinterno = value;
    }

    /**
     * Gets the value of the tiporeference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOREFERENCE() {
        return tiporeference;
    }

    /**
     * Sets the value of the tiporeference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOREFERENCE(String value) {
        this.tiporeference = value;
    }

    /**
     * Gets the value of the rifalfanumerico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRIFALFANUMERICO() {
        return rifalfanumerico;
    }

    /**
     * Sets the value of the rifalfanumerico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRIFALFANUMERICO(String value) {
        this.rifalfanumerico = value;
    }

    /**
     * Gets the value of the rifcontabile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRIFCONTABILE() {
        return rifcontabile;
    }

    /**
     * Sets the value of the rifcontabile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRIFCONTABILE(String value) {
        this.rifcontabile = value;
    }

    /**
     * Gets the value of the rifcodutente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRIFCODUTENTE() {
        return rifcodutente;
    }

    /**
     * Sets the value of the rifcodutente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRIFCODUTENTE(String value) {
        this.rifcodutente = value;
    }

    /**
     * Gets the value of the standardiso property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSTANDARDISO() {
        return standardiso;
    }

    /**
     * Sets the value of the standardiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSTANDARDISO(Boolean value) {
        this.standardiso = value;
    }

}
