//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:46:20 PM CET
//


package it.kdm.docer.sdk.classes.xsd;

import javax.activation.DataHandler;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlMimeType;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the it.kdm.docer.sdk.classes.xsd package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HistoryItemDate_QNAME = new QName("http://classes.sdk.docer.kdm.it/xsd", "date");
    private final static QName _HistoryItemDescription_QNAME = new QName("http://classes.sdk.docer.kdm.it/xsd", "description");
    private final static QName _HistoryItemUser_QNAME = new QName("http://classes.sdk.docer.kdm.it/xsd", "user");
    private final static QName _StreamDescriptorHandler_QNAME = new QName("http://classes.sdk.docer.kdm.it/xsd", "handler");
    private final static QName _LockStatusFullName_QNAME = new QName("http://classes.sdk.docer.kdm.it/xsd", "fullName");
    private final static QName _LockStatusUserId_QNAME = new QName("http://classes.sdk.docer.kdm.it/xsd", "userId");
    private final static QName _KeyValuePairKey_QNAME = new QName("http://classes.sdk.docer.kdm.it/xsd", "key");
    private final static QName _KeyValuePairValue_QNAME = new QName("http://classes.sdk.docer.kdm.it/xsd", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.kdm.docer.sdk.classes.xsd
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KeyValuePair }
     *
     */
    public KeyValuePair createKeyValuePair() {
        return new KeyValuePair();
    }

    /**
     * Create an instance of {@link LockStatus }
     *
     */
    public LockStatus createLockStatus() {
        return new LockStatus();
    }

    /**
     * Create an instance of {@link StreamDescriptor }
     *
     */
    public StreamDescriptor createStreamDescriptor() {
        return new StreamDescriptor();
    }

    /**
     * Create an instance of {@link Version }
     *
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link SearchItem }
     *
     */
    public SearchItem createSearchItem() {
        return new SearchItem();
    }

    /**
     * Create an instance of {@link HistoryItem }
     *
     */
    public HistoryItem createHistoryItem() {
        return new HistoryItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://classes.sdk.docer.kdm.it/xsd", name = "date", scope = HistoryItem.class)
    public JAXBElement<XMLGregorianCalendar> createHistoryItemDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_HistoryItemDate_QNAME, XMLGregorianCalendar.class, HistoryItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://classes.sdk.docer.kdm.it/xsd", name = "description", scope = HistoryItem.class)
    public JAXBElement<String> createHistoryItemDescription(String value) {
        return new JAXBElement<String>(_HistoryItemDescription_QNAME, String.class, HistoryItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://classes.sdk.docer.kdm.it/xsd", name = "user", scope = HistoryItem.class)
    public JAXBElement<String> createHistoryItemUser(String value) {
        return new JAXBElement<String>(_HistoryItemUser_QNAME, String.class, HistoryItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataHandler }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataHandler }{@code >}
     */
    @XmlElementDecl(namespace = "http://classes.sdk.docer.kdm.it/xsd", name = "handler", scope = StreamDescriptor.class)
    @XmlMimeType("application/octet-stream")
    public JAXBElement<DataHandler> createStreamDescriptorHandler(DataHandler value) {
        return new JAXBElement<DataHandler>(_StreamDescriptorHandler_QNAME, DataHandler.class, StreamDescriptor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://classes.sdk.docer.kdm.it/xsd", name = "fullName", scope = LockStatus.class)
    public JAXBElement<String> createLockStatusFullName(String value) {
        return new JAXBElement<String>(_LockStatusFullName_QNAME, String.class, LockStatus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://classes.sdk.docer.kdm.it/xsd", name = "userId", scope = LockStatus.class)
    public JAXBElement<String> createLockStatusUserId(String value) {
        return new JAXBElement<String>(_LockStatusUserId_QNAME, String.class, LockStatus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://classes.sdk.docer.kdm.it/xsd", name = "key", scope = KeyValuePair.class)
    public JAXBElement<String> createKeyValuePairKey(String value) {
        return new JAXBElement<String>(_KeyValuePairKey_QNAME, String.class, KeyValuePair.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://classes.sdk.docer.kdm.it/xsd", name = "value", scope = KeyValuePair.class)
    public JAXBElement<String> createKeyValuePairValue(String value) {
        return new JAXBElement<String>(_KeyValuePairValue_QNAME, String.class, KeyValuePair.class, value);
    }

}
