CREATE TABLE "RATA" 
   (	"ID" NUMBER(38,0) NOT NULL , 
	"DESCRIZIONE" VARCHAR2(250) NOT NULL , 
	"SORT" NUMBER(38,0) NOT NULL , 
	"CF_ISCRITTO" VARCHAR2(50) , 
	"VALORE_RATA" VARCHAR2(20) , 
	"ANNO_SCOLASTICO" VARCHAR2(50) , 
	"MOTIVAZIONE_VARIAZIONE" VARCHAR2(255) , 
	"SCONTO_FAMIGLIA" VARCHAR2(1) , 
	"GIORNI_FREQUENZA" VARCHAR2(5) , 
	"VALORE_CONGUAGLIO" VARCHAR2(20) , 
	 CONSTRAINT "RATA_PKEY" PRIMARY KEY ("ID")
   ) ;

CREATE SEQUENCE RATA_SEQ INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;
   
   
CREATE TABLE "PAGAMENTO" 
   (	"ID" NUMBER(38,0) NOT NULL , 
	"CF_MINORE" VARCHAR2(50)  NOT NULL , 
	"IMPORTO" NUMBER(11,2) NOT NULL , 
	"CF_CONTRIBUENTE" VARCHAR2(50) NOT NULL , 
	"CAUSALE" VARCHAR2(250) , 
	"DOCNUM_PRINCIPALE" VARCHAR2(50) , 
	"MODALITA_ID" NUMBER(38,0) NOT NULL , 
	"RATA_ID" NUMBER(38,0) NOT NULL , 
	"JSON_DOC" VARCHAR2(23767) , 
	 CONSTRAINT "PAGAMENTO_PKEY" PRIMARY KEY ("ID")
   ) ;
COMMENT ON COLUMN "PAGAMENTO"."MODALITA_ID" IS '0: PagoPA, 1: bollettino online, 2: bollettino cartaceo';
  
   
CREATE TABLE "PAGAMENTO_REFEZIONE" 
   (
    "ID_ISTANZA" VARCHAR2(100) , 
	"DATA_PRESENTAZIONE" VARCHAR2(100) , 
	"NUMERO_PROTOCOLLO" VARCHAR2(100) , 
	"DATA_PROTOCOLLO" VARCHAR2(100) , 
	"DOCNUM_PRINCIPALE" VARCHAR2(100) , 
	"DATI_RICHIESTA" VARCHAR2(32767) , 
	"DATI_PAGAMENTO_REFEZIONE" VARCHAR2(32767) , 
	 CONSTRAINT "PAGAMENTO_REFEZIONE_PK" PRIMARY KEY ("ID_ISTANZA")
  );
  
  
  
CREATE TABLE "ISEE" 
(
	"ID" NUMBER,
	"DATA_PRESENTAZIONE" DATE,
	"ANNO" NUMBER(4,0),
	"CODICE_FISCALE" VARCHAR2(100),
	"IMPORTO" NUMBER(11,2),
	"DATA_INIZIO_VALIDITA" DATE,
	"DATA_FINE_VALIDITA" DATE,
	"UTENTE_INSERITORE" VARCHAR2(100),
	"UTENTE_RICHIEDENTE" VARCHAR2(100),
	"CAUSALE" VARCHAR2(2000),
	"DATA_PROTOCOLLO" DATE,
	"NUMERO_PROTOCOLLO" VARCHAR2(100),
	CONSTRAINT "ISEE_PK" PRIMARY KEY ("ID")
);

CREATE SEQUENCE ISEE_SEQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER ;


  
CREATE TABLE "RATA_LOG"
(
	"ID" NUMBER NOT NULL,
	"UTENTE_MODIFICA" VARCHAR2(100),
	"DATA_MODIFICA" DATE,
	"CAUSALE" VARCHAR2(100),
	"ID_RATA" NUMBER,
	"TIPO_MODIFICA" VARCHAR2(20),
	"DATI_RECORD" VARCHAR2(32767),
	CONSTRAINT "RATA_LOG_PK" PRIMARY KEY ("ID")
);

CREATE SEQUENCE RATA_LOG_SEQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER ;


  
CREATE TABLE "ISCRIZIONI_LOG"
(
	"ID" NUMBER NOT NULL,
	"ID_ISTANZA_ISCRIZIONE" VARCHAR2(100),
	"UTENTE_MODIFICA" VARCHAR2(100),
	"DATA_MODIFICA" VARCHAR2(30),
	"CAUSALE" VARCHAR2(100),
	"MOTIVAZIONE" VARCHAR2(1000),
	"DATI_RICHIESTA_PRE" VARCHAR2(32767),
	"DATI_RICHIESTA_POST" VARCHAR2(32767),
	"ESITO_PRE" VARCHAR2(100),
	"ESITO_POST" VARCHAR2(100),
	"TIPO_DOMANDA" VARCHAR2(100),
	CONSTRAINT "ISCRIZIONI_LOG_PK" PRIMARY KEY ("ID")
);

CREATE SEQUENCE ISCRIZIONI_LOG_SEQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER ;



CREATE OR REPLACE VIEW ISCRIZIONI_LOG_VIEW AS
SELECT ID_ISTANZA_ISCRIZIONE, count(ID_ISTANZA_ISCRIZIONE) AS NUM_LOG FROM ISCRIZIONI_LOG GROUP BY ID_ISTANZA_ISCRIZIONE;


CREATE TABLE PORTSCU_ISTANZE (
	ID_COD VARCHAR2(2000),
	NOME_RICHIEDENTE VARCHAR2(2000),
	COGNOME_RICHIEDENTE VARCHAR2(2000),
	TIPO_RICHIEDENTE VARCHAR2(2000),
	NOME_MINORE VARCHAR2(2000),
	COGNOME_MINORE VARCHAR2(2000),
	DATA_NASCITA_MINORE VARCHAR2(2000),
	TIPO_PROCEDIMENTO VARCHAR2(2000),
	NOME_PROCEDIMENTO VARCHAR2(2000),
	EMAIL_UTENTE VARCHAR2(2000),
	DPS_CFRICHIEDENTE VARCHAR2(160),
	DPS_FLGVALUTAZIONE VARCHAR2(30),
	ESITO_VALUTAZIONE VARCHAR2(300),
	FASCIA VARCHAR2(300),
	ID_FAMIGLIA NUMBER,
	NOME_ISTITUTO VARCHAR2(400),
	CF_MINORE_ANAGRAFE VARCHAR2(16),
	CONFERMATA_ISCRIZIONE VARCHAR2(3),
	CONFERMA_NOTIFICATA VARCHAR2(3),
	FASCIA_ORARIA VARCHAR2(200),
	IMPORTO_RETTA NUMBER(11,2),
	DATA_INIZIO_ISCRIZIONE VARCHAR2(20),
	DATA_FINE_ISCRIZIONE VARCHAR2(20),
	RICALCOLO_RATE VARCHAR2(1),
	SCONTO_FAMIGLIA VARCHAR2(1),
	ANNO_SCOLASTICO VARCHAR2(50) , 
	CONSTRAINT PORTSCU_ISTANZE_PK PRIMARY KEY (ID_COD)
);




CREATE SEQUENCE PORTSCU_ISTANZE_SEQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER ;






CREATE TABLE "FASCIA_ISTITUTO" 
(	"ID" NUMBER(38,0) NOT NULL , 
	"CODICE_FISCALE" VARCHAR2(50) NOT NULL , 
	"ANNO_SCOLASTICO" VARCHAR2(50) NOT NULL , 
	"DESCRIZIONE" VARCHAR2(250) NOT NULL , 
	"SORT" NUMBER(11,0) NOT NULL , 
	"NOME_ISTITUTO" VARCHAR2(400) NOT NULL ,
	"FASCIA" VARCHAR2(300) NOT NULL ,
	"FASCIA_ORARIA" VARCHAR2(200) NOT NULL ,
	"RATA_ID" NUMBER(38,0) NULL ,
	CONSTRAINT "FASCIA_ISTITUTO_PKEY" PRIMARY KEY ("ID")
);

CREATE SEQUENCE FASCIA_ISTITUTO_SEQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER ;






























CREATE TABLE ISCRIZIONI_CENTRO_INFANZIA (
	ID NUMBER(38,0),
	NOME_RICHIEDENTE VARCHAR2(2000),
	COGNOME_RICHIEDENTE VARCHAR2(2000),
	TIPO_RICHIEDENTE VARCHAR2(2000),
	NOME_MINORE VARCHAR2(2000),
	COGNOME_MINORE VARCHAR2(2000),
	DATA_NASCITA_MINORE VARCHAR2(2000),
	EMAIL_UTENTE VARCHAR2(2000),
	CF_RICHIEDENTE VARCHAR2(160),
	ESITO_VALUTAZIONE VARCHAR2(300),
	ID_FAMIGLIA NUMBER,
	CF_MINORE VARCHAR2(16),
	CONFERMATA_ISCRIZIONE VARCHAR2(3),
	CONFERMA_NOTIFICATA VARCHAR2(3),
	DATA_INIZIO_ISCRIZIONE VARCHAR2(20),
	DATA_FINE_ISCRIZIONE VARCHAR2(20),
	RICALCOLO_RATE VARCHAR2(1),
	ANNO_SCOLASTICO VARCHAR2(50) , 
	CONSTRAINT ISCRIZIONI_CENTRO_INFANZIA_PK PRIMARY KEY (ID)
);


CREATE SEQUENCE ISCRIZIONI_CENTRO_INFANZIA_SEQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER ;




CREATE TABLE DETTAGLIO_ISCRIZIONI_CENTRO_INFANZIA (
	ID NUMBER(38,0) NOT NULL,
	ID_ISCRIZIONE_CENTRO_INFANZIA NUMBER(38,0) NOT NULL,
	DESCRIZIONE VARCHAR2(250) NOT NULL , 
	SORT NUMBER(11,0) NOT NULL , 
	VALORE_RATA NUMBER(11,2) ,
	VALORE_CONGUAGLIO NUMBER(11,2) ,
	IMPORTO_PAGAMENTO NUMBER(11,2) ,
	CAUSALE_PAGAMENTO VARCHAR2(250) ,
	DOCNUM_PAGAMENTO VARCHAR2(50) , 
	ISTANZA_PAGAMENTO VARCHAR2(100) , 
	MODALITA_ID NUMBER(38,0) , 
	JSON_DOC_PAGAMENTO VARCHAR2(23767) ,
	NOME_ISTITUTO VARCHAR2(400) NOT NULL ,
	FASCIA VARCHAR2(300) NOT NULL ,
	FASCIA_ORARIA VARCHAR2(200) NOT NULL ,
	MOTIVAZIONE_VARIAZIONE VARCHAR2(255) , 
	CONSTRAINT DETTAGLIO_ISCRIZIONI_CENTRO_INFANZIA_PK PRIMARY KEY (ID)
);


CREATE SEQUENCE DETTAGLIO_ISCRIZIONI_CENTRO_INFANZIA_SEQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER ;



CREATE SEQUENCE CENTRO_INFANZIA_LOG_SEQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER ;
  
CREATE TABLE "CENTRO_INFANZIA_LOG"
(
	"ID" NUMBER NOT NULL,
	"UTENTE_MODIFICA" VARCHAR2(100),
	"DATA_MODIFICA" DATE,
	"CAUSALE" VARCHAR2(100),
	"ID_DETTAGLIO_ISCRIZIONE_CENTRO_INFANZIA" NUMBER(38,0),
	"TIPO_MODIFICA" VARCHAR2(20),
	"DATI_PRE" VARCHAR2(32767),
	"DATI_POST" VARCHAR2(32767),
	CONSTRAINT "CENTRO_INFANZIA_PK" PRIMARY KEY ("ID")
);




CREATE TABLE GIORNI_FREQUENZA_ISTITUTO (
	ID NUMBER(38,0) NOT NULL,
	ANNO_SCOLASTICO VARCHAR2(50) , 
	SORT NUMBER(11,0) NOT NULL , 
	DESCRIZIONE VARCHAR2(250) NOT NULL , 
	GIORNI_FREQUENZA NUMBER(5,0) NOT NULL ,
	CONSTRAINT GIORNI_FREQUENZA_ISTITUTO_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE GIORNI_FREQUENZA_ISTITUTO_SEQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER ;






--- 2021-12-23

CREATE TABLE ISCRIZIONI_NIDO_2022
(	"ID_ISTANZA" VARCHAR2(100) , 
	"DOCNUM_DOMANDA" VARCHAR2(100) , 
	"DATA_PRESENTAZIONE" VARCHAR2(100) , 
	"CF_RICHIEDENTE" VARCHAR2(100) , 
	"NUMERO_PROTOCOLLO" VARCHAR2(100) , 
	"ANNO_PROTOCOLLO" VARCHAR2(100) , 
	"DATI_RICHIESTA" VARCHAR2(32767) , 
	"TIPO_RICHIESTA" VARCHAR2(100) , 
	"STATO" VARCHAR2(100) , 
	"PUNTEGGIO" VARCHAR2(100) , 
	CONSTRAINT "ISCRIZIONI_NIDO_2022_PK" PRIMARY KEY ("ID_ISTANZA")
);

CREATE TABLE ISCRIZIONI_INFANZIA_2022
(	"ID_ISTANZA" VARCHAR2(100) , 
	"DOCNUM_DOMANDA" VARCHAR2(100) , 
	"DATA_PRESENTAZIONE" VARCHAR2(100) , 
	"CF_RICHIEDENTE" VARCHAR2(100) , 
	"NUMERO_PROTOCOLLO" VARCHAR2(100) , 
	"ANNO_PROTOCOLLO" VARCHAR2(100) , 
	"DATI_RICHIESTA" VARCHAR2(32767) , 
	"TIPO_RICHIESTA" VARCHAR2(100) , 
	"STATO" VARCHAR2(100) , 
	"PUNTEGGIO" VARCHAR2(100) , 
	CONSTRAINT "ISCRIZIONI_INFANZIA_2022_PK" PRIMARY KEY ("ID_ISTANZA")
);


ALTER TABLE ISEE ADD DOCNUM_PRINCIPALE VARCHAR2(50);


CREATE TABLE ISCRIZIONI_CI_2022
(	"ID_ISTANZA" VARCHAR2(100) , 
	"DOCNUM_DOMANDA" VARCHAR2(100) , 
	"DATA_PRESENTAZIONE" VARCHAR2(100) , 
	"CF_RICHIEDENTE" VARCHAR2(100) , 
	"NUMERO_PROTOCOLLO" VARCHAR2(100) , 
	"ANNO_PROTOCOLLO" VARCHAR2(100) , 
	"DATI_RICHIESTA" VARCHAR2(32767) , 
	"TIPO_RICHIESTA" VARCHAR2(100) , 
	"STATO" VARCHAR2(100) , 
	"PUNTEGGIO" VARCHAR2(100) , 
	CONSTRAINT "ISCRIZIONI_CI_2022_PK" PRIMARY KEY ("ID_ISTANZA")
);

ALTER TABLE ISEE ADD ID_ISTANZA VARCHAR2(100);
ALTER TABLE ISEE ADD STATO VARCHAR2(50);
UPDATE ISEE SET STATO='APPROVATO';




--- 2022-02-21

CREATE TABLE "DOMANDA_FORNITURA_LIBRI" 
(	
	"ID_ISTANZA" VARCHAR2(200) ,
	"CF_RICHIEDENTE" VARCHAR2(40) ,
	"CF_MINORE" VARCHAR2(40) ,
	"DATI_RICHIESTA" VARCHAR2(32767) ,
	"DATA_PRESENTAZIONE" VARCHAR2(40) ,
	"NUMERO_PROTOCOLLO" VARCHAR2(40) ,
	"ANNO_PROTOCOLLO" VARCHAR2(40) ,
	"DOCNUM_PRINCIPALE" VARCHAR2(40) ,
	"ANNULLATO" VARCHAR2(1) ,
	"ID_ISTANZA_ANNULLAMENTO" VARCHAR2(40) ,
	"DATI_RICHIESTA_ANNULLAMENTO" VARCHAR2(32767) ,
	"DATA_PRESENTAZIONE_ANNULLAMENTO" VARCHAR2(40) ,
	"NUMERO_PROTOCOLLO_ANNULLAMENTO" VARCHAR2(40) ,
	"ANNO_PROTOCOLLO_ANNULLAMENTO" VARCHAR2(40) ,
	"DOCNUM_PRINCIPALE_ANNULLAMENTO" VARCHAR2(40) ,
	"ANNO_SCOLASTICO" VARCHAR2(50) ,
	CONSTRAINT "DOMANDA_FORNITURA_LIBRI_PK" PRIMARY KEY ("ID_ISTANZA")
);