//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 11:06:38 AM CET 
//


package it.kdm.docer.firma;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.kdm.docer.firma package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WSFirmaFirmaExceptionFirmaException_QNAME = new QName("http://firma.docer.kdm.it", "FirmaException");
    private final static QName _FirmaAutomaticaFileToken_QNAME = new QName("http://firma.docer.kdm.it", "token");
    private final static QName _FirmaAutomaticaFileAlias_QNAME = new QName("http://firma.docer.kdm.it", "alias");
    private final static QName _FirmaAutomaticaFilePin_QNAME = new QName("http://firma.docer.kdm.it", "pin");
    private final static QName _FirmaAutomaticaFileTipo_QNAME = new QName("http://firma.docer.kdm.it", "tipo");
    private final static QName _FirmaRemotaOTP_QNAME = new QName("http://firma.docer.kdm.it", "OTP");
    private final static QName _RequestOTPResponseReturn_QNAME = new QName("http://firma.docer.kdm.it", "return");
    private final static QName _LoginSSOSaml_QNAME = new QName("http://firma.docer.kdm.it", "saml");
    private final static QName _LoginSSOCodiceEnte_QNAME = new QName("http://firma.docer.kdm.it", "codiceEnte");
    private final static QName _WriteConfigXmlConfig_QNAME = new QName("http://firma.docer.kdm.it", "xmlConfig");
    private final static QName _LoginUserId_QNAME = new QName("http://firma.docer.kdm.it", "userId");
    private final static QName _LoginPassword_QNAME = new QName("http://firma.docer.kdm.it", "password");
    private final static QName _StreamDescriptorDataHandler_QNAME = new QName("http://model.firma.docer.kdm.it/xsd", "dataHandler");
    private final static QName _StreamDescriptorDocNum_QNAME = new QName("http://model.firma.docer.kdm.it/xsd", "docNum");
    private final static QName _StreamDescriptorMessage_QNAME = new QName("http://model.firma.docer.kdm.it/xsd", "message");
    private final static QName _StreamDescriptorName_QNAME = new QName("http://model.firma.docer.kdm.it/xsd", "name");
    private final static QName _StreamDescriptorOriginalName_QNAME = new QName("http://model.firma.docer.kdm.it/xsd", "originalName");
    private final static QName _KeyValuePairDFFileName_QNAME = new QName("http://model.firma.docer.kdm.it/xsd", "fileName");
    private final static QName _KeyValuePairDFStream_QNAME = new QName("http://model.firma.docer.kdm.it/xsd", "stream");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.kdm.docer.firma
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSFirmaFirmaException }
     * 
     */
    public WSFirmaFirmaException createWSFirmaFirmaException() {
        return new WSFirmaFirmaException();
    }

    /**
     * Create an instance of {@link FirmaException }
     * 
     */
    public FirmaException createFirmaException() {
        return new FirmaException();
    }

    /**
     * Create an instance of {@link FirmaAutomaticaFile }
     * 
     */
    public FirmaAutomaticaFile createFirmaAutomaticaFile() {
        return new FirmaAutomaticaFile();
    }

    /**
     * Create an instance of {@link KeyValuePairDF }
     * 
     */
    public KeyValuePairDF createKeyValuePairDF() {
        return new KeyValuePairDF();
    }

    /**
     * Create an instance of {@link FirmaAutomaticaFileResponse }
     * 
     */
    public FirmaAutomaticaFileResponse createFirmaAutomaticaFileResponse() {
        return new FirmaAutomaticaFileResponse();
    }

    /**
     * Create an instance of {@link StreamDescriptor }
     * 
     */
    public StreamDescriptor createStreamDescriptor() {
        return new StreamDescriptor();
    }

    /**
     * Create an instance of {@link FirmaAutomatica }
     * 
     */
    public FirmaAutomatica createFirmaAutomatica() {
        return new FirmaAutomatica();
    }

    /**
     * Create an instance of {@link FirmaAutomaticaResponse }
     * 
     */
    public FirmaAutomaticaResponse createFirmaAutomaticaResponse() {
        return new FirmaAutomaticaResponse();
    }

    /**
     * Create an instance of {@link FirmaRemota }
     * 
     */
    public FirmaRemota createFirmaRemota() {
        return new FirmaRemota();
    }

    /**
     * Create an instance of {@link FirmaRemotaResponse }
     * 
     */
    public FirmaRemotaResponse createFirmaRemotaResponse() {
        return new FirmaRemotaResponse();
    }

    /**
     * Create an instance of {@link RequestOTP }
     * 
     */
    public RequestOTP createRequestOTP() {
        return new RequestOTP();
    }

    /**
     * Create an instance of {@link RequestOTPResponse }
     * 
     */
    public RequestOTPResponse createRequestOTPResponse() {
        return new RequestOTPResponse();
    }

    /**
     * Create an instance of {@link FirmaRemotaFile }
     * 
     */
    public FirmaRemotaFile createFirmaRemotaFile() {
        return new FirmaRemotaFile();
    }

    /**
     * Create an instance of {@link FirmaRemotaFileResponse }
     * 
     */
    public FirmaRemotaFileResponse createFirmaRemotaFileResponse() {
        return new FirmaRemotaFileResponse();
    }

    /**
     * Create an instance of {@link LoginSSO }
     * 
     */
    public LoginSSO createLoginSSO() {
        return new LoginSSO();
    }

    /**
     * Create an instance of {@link LoginSSOResponse }
     * 
     */
    public LoginSSOResponse createLoginSSOResponse() {
        return new LoginSSOResponse();
    }

    /**
     * Create an instance of {@link WriteConfig }
     * 
     */
    public WriteConfig createWriteConfig() {
        return new WriteConfig();
    }

    /**
     * Create an instance of {@link WriteConfigResponse }
     * 
     */
    public WriteConfigResponse createWriteConfigResponse() {
        return new WriteConfigResponse();
    }

    /**
     * Create an instance of {@link ReadConfig }
     * 
     */
    public ReadConfig createReadConfig() {
        return new ReadConfig();
    }

    /**
     * Create an instance of {@link ReadConfigResponse }
     * 
     */
    public ReadConfigResponse createReadConfigResponse() {
        return new ReadConfigResponse();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link Logout }
     * 
     */
    public Logout createLogout() {
        return new Logout();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FirmaException }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FirmaException }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "FirmaException", scope = WSFirmaFirmaException.class)
    public JAXBElement<FirmaException> createWSFirmaFirmaExceptionFirmaException(FirmaException value) {
        return new JAXBElement<FirmaException>(_WSFirmaFirmaExceptionFirmaException_QNAME, FirmaException.class, WSFirmaFirmaException.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "token", scope = FirmaAutomaticaFile.class)
    public JAXBElement<String> createFirmaAutomaticaFileToken(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileToken_QNAME, String.class, FirmaAutomaticaFile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "alias", scope = FirmaAutomaticaFile.class)
    public JAXBElement<String> createFirmaAutomaticaFileAlias(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileAlias_QNAME, String.class, FirmaAutomaticaFile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "pin", scope = FirmaAutomaticaFile.class)
    public JAXBElement<String> createFirmaAutomaticaFilePin(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFilePin_QNAME, String.class, FirmaAutomaticaFile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "tipo", scope = FirmaAutomaticaFile.class)
    public JAXBElement<String> createFirmaAutomaticaFileTipo(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileTipo_QNAME, String.class, FirmaAutomaticaFile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "token", scope = FirmaAutomatica.class)
    public JAXBElement<String> createFirmaAutomaticaToken(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileToken_QNAME, String.class, FirmaAutomatica.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "alias", scope = FirmaAutomatica.class)
    public JAXBElement<String> createFirmaAutomaticaAlias(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileAlias_QNAME, String.class, FirmaAutomatica.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "pin", scope = FirmaAutomatica.class)
    public JAXBElement<String> createFirmaAutomaticaPin(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFilePin_QNAME, String.class, FirmaAutomatica.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "tipo", scope = FirmaAutomatica.class)
    public JAXBElement<String> createFirmaAutomaticaTipo(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileTipo_QNAME, String.class, FirmaAutomatica.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "token", scope = FirmaRemota.class)
    public JAXBElement<String> createFirmaRemotaToken(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileToken_QNAME, String.class, FirmaRemota.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "alias", scope = FirmaRemota.class)
    public JAXBElement<String> createFirmaRemotaAlias(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileAlias_QNAME, String.class, FirmaRemota.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "pin", scope = FirmaRemota.class)
    public JAXBElement<String> createFirmaRemotaPin(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFilePin_QNAME, String.class, FirmaRemota.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "tipo", scope = FirmaRemota.class)
    public JAXBElement<String> createFirmaRemotaTipo(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileTipo_QNAME, String.class, FirmaRemota.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "OTP", scope = FirmaRemota.class)
    public JAXBElement<String> createFirmaRemotaOTP(String value) {
        return new JAXBElement<String>(_FirmaRemotaOTP_QNAME, String.class, FirmaRemota.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "token", scope = RequestOTP.class)
    public JAXBElement<String> createRequestOTPToken(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileToken_QNAME, String.class, RequestOTP.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "alias", scope = RequestOTP.class)
    public JAXBElement<String> createRequestOTPAlias(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileAlias_QNAME, String.class, RequestOTP.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "pin", scope = RequestOTP.class)
    public JAXBElement<String> createRequestOTPPin(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFilePin_QNAME, String.class, RequestOTP.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "return", scope = RequestOTPResponse.class)
    public JAXBElement<String> createRequestOTPResponseReturn(String value) {
        return new JAXBElement<String>(_RequestOTPResponseReturn_QNAME, String.class, RequestOTPResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "token", scope = FirmaRemotaFile.class)
    public JAXBElement<String> createFirmaRemotaFileToken(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileToken_QNAME, String.class, FirmaRemotaFile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "alias", scope = FirmaRemotaFile.class)
    public JAXBElement<String> createFirmaRemotaFileAlias(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileAlias_QNAME, String.class, FirmaRemotaFile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "pin", scope = FirmaRemotaFile.class)
    public JAXBElement<String> createFirmaRemotaFilePin(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFilePin_QNAME, String.class, FirmaRemotaFile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "tipo", scope = FirmaRemotaFile.class)
    public JAXBElement<String> createFirmaRemotaFileTipo(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileTipo_QNAME, String.class, FirmaRemotaFile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "OTP", scope = FirmaRemotaFile.class)
    public JAXBElement<String> createFirmaRemotaFileOTP(String value) {
        return new JAXBElement<String>(_FirmaRemotaOTP_QNAME, String.class, FirmaRemotaFile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "saml", scope = LoginSSO.class)
    public JAXBElement<String> createLoginSSOSaml(String value) {
        return new JAXBElement<String>(_LoginSSOSaml_QNAME, String.class, LoginSSO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "codiceEnte", scope = LoginSSO.class)
    public JAXBElement<String> createLoginSSOCodiceEnte(String value) {
        return new JAXBElement<String>(_LoginSSOCodiceEnte_QNAME, String.class, LoginSSO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "return", scope = LoginSSOResponse.class)
    public JAXBElement<String> createLoginSSOResponseReturn(String value) {
        return new JAXBElement<String>(_RequestOTPResponseReturn_QNAME, String.class, LoginSSOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "token", scope = WriteConfig.class)
    public JAXBElement<String> createWriteConfigToken(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileToken_QNAME, String.class, WriteConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "xmlConfig", scope = WriteConfig.class)
    public JAXBElement<String> createWriteConfigXmlConfig(String value) {
        return new JAXBElement<String>(_WriteConfigXmlConfig_QNAME, String.class, WriteConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "token", scope = ReadConfig.class)
    public JAXBElement<String> createReadConfigToken(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileToken_QNAME, String.class, ReadConfig.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "return", scope = ReadConfigResponse.class)
    public JAXBElement<String> createReadConfigResponseReturn(String value) {
        return new JAXBElement<String>(_RequestOTPResponseReturn_QNAME, String.class, ReadConfigResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "userId", scope = Login.class)
    public JAXBElement<String> createLoginUserId(String value) {
        return new JAXBElement<String>(_LoginUserId_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "password", scope = Login.class)
    public JAXBElement<String> createLoginPassword(String value) {
        return new JAXBElement<String>(_LoginPassword_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "codiceEnte", scope = Login.class)
    public JAXBElement<String> createLoginCodiceEnte(String value) {
        return new JAXBElement<String>(_LoginSSOCodiceEnte_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "return", scope = LoginResponse.class)
    public JAXBElement<String> createLoginResponseReturn(String value) {
        return new JAXBElement<String>(_RequestOTPResponseReturn_QNAME, String.class, LoginResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://firma.docer.kdm.it", name = "token", scope = Logout.class)
    public JAXBElement<String> createLogoutToken(String value) {
        return new JAXBElement<String>(_FirmaAutomaticaFileToken_QNAME, String.class, Logout.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://model.firma.docer.kdm.it/xsd", name = "dataHandler", scope = StreamDescriptor.class)
    public JAXBElement<byte[]> createStreamDescriptorDataHandler(byte[] value) {
        return new JAXBElement<byte[]>(_StreamDescriptorDataHandler_QNAME, byte[].class, StreamDescriptor.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://model.firma.docer.kdm.it/xsd", name = "docNum", scope = StreamDescriptor.class)
    public JAXBElement<String> createStreamDescriptorDocNum(String value) {
        return new JAXBElement<String>(_StreamDescriptorDocNum_QNAME, String.class, StreamDescriptor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://model.firma.docer.kdm.it/xsd", name = "message", scope = StreamDescriptor.class)
    public JAXBElement<String> createStreamDescriptorMessage(String value) {
        return new JAXBElement<String>(_StreamDescriptorMessage_QNAME, String.class, StreamDescriptor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://model.firma.docer.kdm.it/xsd", name = "name", scope = StreamDescriptor.class)
    public JAXBElement<String> createStreamDescriptorName(String value) {
        return new JAXBElement<String>(_StreamDescriptorName_QNAME, String.class, StreamDescriptor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://model.firma.docer.kdm.it/xsd", name = "originalName", scope = StreamDescriptor.class)
    public JAXBElement<String> createStreamDescriptorOriginalName(String value) {
        return new JAXBElement<String>(_StreamDescriptorOriginalName_QNAME, String.class, StreamDescriptor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://model.firma.docer.kdm.it/xsd", name = "fileName", scope = KeyValuePairDF.class)
    public JAXBElement<String> createKeyValuePairDFFileName(String value) {
        return new JAXBElement<String>(_KeyValuePairDFFileName_QNAME, String.class, KeyValuePairDF.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://model.firma.docer.kdm.it/xsd", name = "stream", scope = KeyValuePairDF.class)
    public JAXBElement<byte[]> createKeyValuePairDFStream(byte[] value) {
        return new JAXBElement<byte[]>(_KeyValuePairDFStream_QNAME, byte[].class, KeyValuePairDF.class, ((byte[]) value));
    }

}
