
package it.filippetti.ks.api.payment.pmpay.paypa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PayPA", targetNamespace = "http://pmpay.it/ws/payPA/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PayPA {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Pagamento", action = "http://pmpay.it/ws/payPA/Pagamento")
    @WebResult(name = "response", targetNamespace = "http://pmpay.it/ws/payPA/")
    @RequestWrapper(localName = "Pagamento", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.Pagamento")
    @ResponseWrapper(localName = "PagamentoResponse", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.PagamentoResponse")
    public String pagamento(
        @WebParam(name = "request", targetNamespace = "http://pmpay.it/ws/payPA/")
        String request);

    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRT", action = "http://pmpay.it/ws/payPA/GetRT")
    @WebResult(name = "GetRTResult", targetNamespace = "http://pmpay.it/ws/payPA/")
    @RequestWrapper(localName = "GetRT", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.GetRT")
    @ResponseWrapper(localName = "GetRTResponse", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.GetRTResponse")
    public String getRT(
        @WebParam(name = "content", targetNamespace = "http://pmpay.it/ws/payPA/")
        String content);

    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBOLLO", action = "http://pmpay.it/ws/payPA/GetBOLLO")
    @WebResult(name = "GetBOLLOResponse", targetNamespace = "http://pmpay.it/ws/payPA/")
    @RequestWrapper(localName = "GetBOLLO", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.GetBOLLO")
    @ResponseWrapper(localName = "GetBOLLOResponse", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.GetBOLLOResponse")
    public String getBOLLO(
        @WebParam(name = "content", targetNamespace = "http://pmpay.it/ws/payPA/")
        String content);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PagamentoEsistente", action = "http://pmpay.it/ws/payPA/PagamentoEsistente")
    @WebResult(name = "PagamentoEsistenteResult", targetNamespace = "http://pmpay.it/ws/payPA/")
    @RequestWrapper(localName = "PagamentoEsistente", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.PagamentoEsistente")
    @ResponseWrapper(localName = "PagamentoEsistenteResponse", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.PagamentoEsistenteResponse")
    public String pagamentoEsistente(
        @WebParam(name = "request", targetNamespace = "http://pmpay.it/ws/payPA/")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegistraPagamento", action = "http://pmpay.it/ws/payPA/RegistraPagamento")
    @WebResult(name = "response", targetNamespace = "http://pmpay.it/ws/payPA/")
    @RequestWrapper(localName = "RegistraPagamento", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.RegistraPagamento")
    @ResponseWrapper(localName = "RegistraPagamentoResponse", targetNamespace = "http://pmpay.it/ws/payPA/", className = "it.pmpay.ws.paypa.RegistraPagamentoResponse")
    public String registraPagamento(
        @WebParam(name = "request", targetNamespace = "http://pmpay.it/ws/payPA/")
        String request);

}
