//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 06:06:44 PM CEST 
//


package it.filippetti.ks.api.payment.pmpay.paypa.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pmpay package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RICHIEDIRTRESPONSE_QNAME = new QName("urn:pmpay", "RICHIEDI_RT_RESPONSE");
    private final static QName _PAGAMENTOREQUEST_QNAME = new QName("urn:pmpay", "PAGAMENTO_REQUEST");
    private final static QName _PAGAMENTORESPONSE_QNAME = new QName("urn:pmpay", "PAGAMENTO_RESPONSE");
    private final static QName _RICHIEDIRTREQUEST_QNAME = new QName("urn:pmpay", "RICHIEDI_RT_REQUEST");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pmpay
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RICHIEDIRTRESPONSE }
     * 
     */
    public RICHIEDIRTRESPONSE createRICHIEDIRTRESPONSE() {
        return new RICHIEDIRTRESPONSE();
    }

    /**
     * Create an instance of {@link PAGAMENTOREQUEST }
     * 
     */
    public PAGAMENTOREQUEST createPAGAMENTOREQUEST() {
        return new PAGAMENTOREQUEST();
    }

    /**
     * Create an instance of {@link PAGAMENTORESPONSE }
     * 
     */
    public PAGAMENTORESPONSE createPAGAMENTORESPONSE() {
        return new PAGAMENTORESPONSE();
    }

    /**
     * Create an instance of {@link RICHIEDIRTREQUEST }
     * 
     */
    public RICHIEDIRTREQUEST createRICHIEDIRTREQUEST() {
        return new RICHIEDIRTREQUEST();
    }

    /**
     * Create an instance of {@link RichiestaRT }
     * 
     */
    public RichiestaRT createRichiestaRT() {
        return new RichiestaRT();
    }

    /**
     * Create an instance of {@link HeaderPagamento }
     * 
     */
    public HeaderPagamento createHeaderPagamento() {
        return new HeaderPagamento();
    }

    /**
     * Create an instance of {@link HeaderRichiestaRT }
     * 
     */
    public HeaderRichiestaRT createHeaderRichiestaRT() {
        return new HeaderRichiestaRT();
    }

    /**
     * Create an instance of {@link Pagamento }
     * 
     */
    public Pagamento createPagamento() {
        return new Pagamento();
    }

    /**
     * Create an instance of {@link AnagraficaPagamento }
     * 
     */
    public AnagraficaPagamento createAnagraficaPagamento() {
        return new AnagraficaPagamento();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RICHIEDIRTRESPONSE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:pmpay", name = "RICHIEDI_RT_RESPONSE")
    public JAXBElement<RICHIEDIRTRESPONSE> createRICHIEDIRTRESPONSE(RICHIEDIRTRESPONSE value) {
        return new JAXBElement<RICHIEDIRTRESPONSE>(_RICHIEDIRTRESPONSE_QNAME, RICHIEDIRTRESPONSE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PAGAMENTOREQUEST }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:pmpay", name = "PAGAMENTO_REQUEST")
    public JAXBElement<PAGAMENTOREQUEST> createPAGAMENTOREQUEST(PAGAMENTOREQUEST value) {
        return new JAXBElement<PAGAMENTOREQUEST>(_PAGAMENTOREQUEST_QNAME, PAGAMENTOREQUEST.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PAGAMENTORESPONSE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:pmpay", name = "PAGAMENTO_RESPONSE")
    public JAXBElement<PAGAMENTORESPONSE> createPAGAMENTORESPONSE(PAGAMENTORESPONSE value) {
        return new JAXBElement<PAGAMENTORESPONSE>(_PAGAMENTORESPONSE_QNAME, PAGAMENTORESPONSE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RICHIEDIRTREQUEST }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:pmpay", name = "RICHIEDI_RT_REQUEST")
    public JAXBElement<RICHIEDIRTREQUEST> createRICHIEDIRTREQUEST(RICHIEDIRTREQUEST value) {
        return new JAXBElement<RICHIEDIRTREQUEST>(_RICHIEDIRTREQUEST_QNAME, RICHIEDIRTREQUEST.class, null, value);
    }

}
