//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 06:06:44 PM CEST 
//


package it.filippetti.ks.api.payment.pmpay.paypa.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PAGAMENTO_REQUEST complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PAGAMENTO_REQUEST">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="headerPagamento" type="{urn:pmpay}headerPagamento"/>
 *         &lt;element name="anagraficaPagamento" type="{urn:pmpay}anagraficaPagamento"/>
 *         &lt;element name="pagamento" type="{urn:pmpay}pagamento" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PAGAMENTO_REQUEST", propOrder = {
    "headerPagamento",
    "anagraficaPagamento",
    "pagamento"
})
public class PAGAMENTOREQUEST {

    @XmlElement(required = true)
    protected HeaderPagamento headerPagamento;
    @XmlElement(required = true)
    protected AnagraficaPagamento anagraficaPagamento;
    @XmlElement(required = true)
    protected List<Pagamento> pagamento;

    /**
     * Gets the value of the headerPagamento property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderPagamento }
     *     
     */
    public HeaderPagamento getHeaderPagamento() {
        return headerPagamento;
    }

    /**
     * Sets the value of the headerPagamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderPagamento }
     *     
     */
    public void setHeaderPagamento(HeaderPagamento value) {
        this.headerPagamento = value;
    }

    /**
     * Gets the value of the anagraficaPagamento property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaPagamento }
     *     
     */
    public AnagraficaPagamento getAnagraficaPagamento() {
        return anagraficaPagamento;
    }

    /**
     * Sets the value of the anagraficaPagamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaPagamento }
     *     
     */
    public void setAnagraficaPagamento(AnagraficaPagamento value) {
        this.anagraficaPagamento = value;
    }

    /**
     * Gets the value of the pagamento property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pagamento property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPagamento().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pagamento }
     * 
     * 
     */
    public List<Pagamento> getPagamento() {
        if (pagamento == null) {
            pagamento = new ArrayList<Pagamento>();
        }
        return this.pagamento;
    }

}
