server:
    port: 8086

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/form?serverTimezone=UTC&rewriteBatchedStatements=true
        username: username
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57InnoDBDialect      
        
env:
    systemProperties:
        - name: docer.url
          value:  http://localhost:8080
          
application:
    preview:
        externalUrl: http://ks-backoffice:8082/~form-preview?formId=$formId
        assetsBaseUrl: http://ks-backoffice:8082/static/   