server:
    port: 8091

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/payment?serverTimezone=UTC&rewriteBatchedStatements=true
        username: username
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        
env:
    systemProperties:
        - name: docer.url
          value:  http://localhost:8080
          
application:
    baseUrl: http://ks-portal:8082/pagamenti/v1
    portalBaseUrl: http://ks-portal:8082
    portalAPIBaseUrl: http://localhost:8084
    ksUtilsAPIBaseUrl: http://localhost.0.135:8085
    docerAPIBaseUrl: http://localhost:8080
    expiryTimeInHours: 2
    pagoPAUrl: https://secure.pmpay.it/

    
    