/*
installare DB SERVER MYSQL5.5

Accedere alla linea di comando di MySQL...
Come root.

mysql -uroot -p
*/

DROP TABLE IF EXISTS CCD_JOB;
DROP SEQUENCE IF EXISTS CCD_JOB_id_seq;
CREATE SEQUENCE CCD_JOB_id_seq;
CREATE TABLE CCD_JOB
(
  ID_JOB			BIGINT DEFAULT nextval('CCD_JOB_id_seq') NOT NULL,
  CHIAVE_DOC	        VARCHAR(50),
  STATO               		VARCHAR(3) NOT NULL,
  COD_ENTE             VARCHAR(100),
  COD_AOO             VARCHAR(100),
  DT_INS			TIMESTAMP, 
  DT_ULT_MOD          		TIMESTAMP, 
  DT_CHIAMATA         		TIMESTAMP, 
  WEB_SERVICE			VARCHAR(10), 
  docId               		BIGINT NOT NULL,		
  XML_PROFILO_DOC_PRINCIPALE 	TEXT, 			
  XML_PROFILO_DOC_ALLEGATI	TEXT,				
  LISTA_URI 			TEXT,					
  TIPO_DOC			VARCHAR(100),			
  APP_CHIAMANTE 		VARCHAR(50),			
  TIPO_CONSERVAZIONE 		VARCHAR(30),			
  FORZA_COLLEGAMENTO 		VARCHAR(5), 			
  FORZA_ACCETTAZIONE 		VARCHAR(5), 			
  FORZA_CONSERVAZIONE 		VARCHAR(5), 			
  DATA_REGISTRAZIONE 		VARCHAR(50),
  ERRCODE			VARCHAR(15),
  MESSAGE			TEXT,
  PRIMARY KEY (ID_JOB)
);

	
DROP TABLE IF EXISTS CCD_JOB_LOG;
DROP SEQUENCE IF EXISTS CCD_JOB_LOG_id_seq;
CREATE SEQUENCE CCD_JOB_LOG_id_seq;
CREATE TABLE CCD_JOB_LOG
(
  ID_LOG			BIGINT DEFAULT nextval('CCD_JOB_LOG_id_seq') NOT NULL,
  ID_JOB              		BIGINT,
  CHIAVE_DOC	        VARCHAR(50),
  docId              		BIGINT NOT NULL,
  ESITO				VARCHAR(4),
  DT_INS			TIMESTAMP,
  DT_CHIAMATA         		TIMESTAMP,
  DT_RISPOSTA         		TIMESTAMP,
  ERRCODE			VARCHAR(15),
  MESSAGE			TEXT,
  XML_PROFILO_DOC_PRINCIPALE 	TEXT, 
  XML_PROFILO_DOC_ALLEGATI	TEXT, 
  LISTA_URI 			TEXT, 
  TIPO_DOC			VARCHAR(100),
  APP_CHIAMANTE 		VARCHAR(50), 	
  TIPO_CONSERVAZIONE 		VARCHAR(30), 
  FORZA_COLLEGAMENTO 		VARCHAR(5),  
  FORZA_ACCETTAZIONE 		VARCHAR(5),  
  FORZA_CONSERVAZIONE 		VARCHAR(5),  
  DATA_REGISTRAZIONE 		VARCHAR(50), 
  WEB_SERVICE			VARCHAR(10),
  XML_RICHIESTA			TEXT,
  XML_ESITO			TEXT,
  PRIMARY KEY (ID_LOG)
);
